baseURL = "https://elisewright.github.io/SavingSouls/"
languageCode = "en-us"
title = "SavingSouls"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Elise Wright"
    description = "Brent William Wright has a calling from God to spread his word and bring people to him. His sermons are profound and well presented. Any comments are most welcome."
    githubUsername = "#"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/tags/sermons"
    name = "Sermons"
    weight = 3

[[menu.main]]
    url = "/tags/daily devotions"
    name = "Daily Devotions"
    weight = 4    

[[menu.main]]
    url = "/post/music.canata/"
    name = "Cantata"
    weight = 5

[[menu.main]]
    url = "/tags/africa/"
    name = "Africa"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:savingsouls13@gmail.com"
    name = "envelope-o"
    weight = 1